/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHlasyRouteImport } from './routes/_authenticated/hlasy'
import { Route as AuthenticatedHudbaRouteImport } from './routes/_authenticated/hudba'
import { Route as AuthenticatedNastaveniRouteImport } from './routes/_authenticated/nastaveni'
import { Route as AuthenticatedProjektyRouteImport } from './routes/_authenticated/projekty'
import { Route as AuthenticatedSablonyRouteImport } from './routes/_authenticated/sablony'
import { Route as AuthenticatedProjektIdRouteImport } from './routes/_authenticated/projekt.$id'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHlasyRoute = AuthenticatedHlasyRouteImport.update({
  id: '/_authenticated/hlasy',
  path: '/hlasy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHudbaRoute = AuthenticatedHudbaRouteImport.update({
  id: '/_authenticated/hudba',
  path: '/hudba',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNastaveniRoute = AuthenticatedNastaveniRouteImport.update({
  id: '/_authenticated/nastaveni',
  path: '/nastaveni',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjektyRoute = AuthenticatedProjektyRouteImport.update({
  id: '/_authenticated/projekty',
  path: '/projekty',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSablonyRoute = AuthenticatedSablonyRouteImport.update({
  id: '/_authenticated/sablony',
  path: '/sablony',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjektIdRoute = AuthenticatedProjektIdRouteImport.update({
  id: '/_authenticated/projekt/$id',
  path: '/projekt/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hlasy': typeof AuthenticatedHlasyRoute
  '/hudba': typeof AuthenticatedHudbaRoute
  '/nastaveni': typeof AuthenticatedNastaveniRoute
  '/projekty': typeof AuthenticatedProjektyRoute
  '/sablony': typeof AuthenticatedSablonyRoute
  '/': typeof AuthenticatedIndexRoute
  '/projekt/$id': typeof AuthenticatedProjektIdRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hlasy': typeof AuthenticatedHlasyRoute
  '/hudba': typeof AuthenticatedHudbaRoute
  '/nastaveni': typeof AuthenticatedNastaveniRoute
  '/projekty': typeof AuthenticatedProjektyRoute
  '/sablony': typeof AuthenticatedSablonyRoute
  '/': typeof AuthenticatedIndexRoute
  '/projekt/$id': typeof AuthenticatedProjektIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/hlasy': typeof AuthenticatedHlasyRoute
  '/_authenticated/hudba': typeof AuthenticatedHudbaRoute
  '/_authenticated/nastaveni': typeof AuthenticatedNastaveniRoute
  '/_authenticated/projekty': typeof AuthenticatedProjektyRoute
  '/_authenticated/sablony': typeof AuthenticatedSablonyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/projekt/$id': typeof AuthenticatedProjektIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/hlasy'
    | '/hudba'
    | '/nastaveni'
    | '/projekty'
    | '/sablony'
    | '/'
    | '/projekt/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/hlasy'
    | '/hudba'
    | '/nastaveni'
    | '/projekty'
    | '/sablony'
    | '/'
    | '/projekt/$id'
  id:
    | '__root__'
    | '/_authenticated/dashboard'
    | '/_authenticated/hlasy'
    | '/_authenticated/hudba'
    | '/_authenticated/nastaveni'
    | '/_authenticated/projekty'
    | '/_authenticated/sablony'
    | '/_authenticated/'
    | '/_authenticated/projekt/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHlasyRoute: typeof AuthenticatedHlasyRoute
  AuthenticatedHudbaRoute: typeof AuthenticatedHudbaRoute
  AuthenticatedNastaveniRoute: typeof AuthenticatedNastaveniRoute
  AuthenticatedProjektyRoute: typeof AuthenticatedProjektyRoute
  AuthenticatedSablonyRoute: typeof AuthenticatedSablonyRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProjektIdRoute: typeof AuthenticatedProjektIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/hlasy': {
      id: '/_authenticated/hlasy'
      path: '/hlasy'
      fullPath: '/hlasy'
      preLoaderRoute: typeof AuthenticatedHlasyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/hudba': {
      id: '/_authenticated/hudba'
      path: '/hudba'
      fullPath: '/hudba'
      preLoaderRoute: typeof AuthenticatedHudbaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/nastaveni': {
      id: '/_authenticated/nastaveni'
      path: '/nastaveni'
      fullPath: '/nastaveni'
      preLoaderRoute: typeof AuthenticatedNastaveniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projekty': {
      id: '/_authenticated/projekty'
      path: '/projekty'
      fullPath: '/projekty'
      preLoaderRoute: typeof AuthenticatedProjektyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sablony': {
      id: '/_authenticated/sablony'
      path: '/sablony'
      fullPath: '/sablony'
      preLoaderRoute: typeof AuthenticatedSablonyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projekt/$id': {
      id: '/_authenticated/projekt/$id'
      path: '/projekt/$id'
      fullPath: '/projekt/$id'
      preLoaderRoute: typeof AuthenticatedProjektIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHlasyRoute: AuthenticatedHlasyRoute,
  AuthenticatedHudbaRoute: AuthenticatedHudbaRoute,
  AuthenticatedNastaveniRoute: AuthenticatedNastaveniRoute,
  AuthenticatedProjektyRoute: AuthenticatedProjektyRoute,
  AuthenticatedSablonyRoute: AuthenticatedSablonyRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProjektIdRoute: AuthenticatedProjektIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
