/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjektyRouteImport } from './routes/projekty'
import { Route as ProjektIdRouteImport } from './routes/projekt.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektyRoute = ProjektyRouteImport.update({
  id: '/projekty',
  path: '/projekty',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektIdRoute = ProjektIdRouteImport.update({
  id: '/projekt/$id',
  path: '/projekt/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projekty': typeof ProjektyRoute
  '/projekt/$id': typeof ProjektIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projekty': typeof ProjektyRoute
  '/projekt/$id': typeof ProjektIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projekty': typeof ProjektyRoute
  '/projekt/$id': typeof ProjektIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projekty' | '/projekt/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projekty' | '/projekt/$id'
  id: '__root__' | '/' | '/projekty' | '/projekt/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjektyRoute: typeof ProjektyRoute
  ProjektIdRoute: typeof ProjektIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekty': {
      id: '/projekty'
      path: '/projekty'
      fullPath: '/projekty'
      preLoaderRoute: typeof ProjektyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekt/$id': {
      id: '/projekt/$id'
      path: '/projekt/$id'
      fullPath: '/projekt/$id'
      preLoaderRoute: typeof ProjektIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjektyRoute: ProjektyRoute,
  ProjektIdRoute: ProjektIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
